version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd src/backend
            mvn -B -DskipTests clean package
      - run:
          name: Test
          command: |
            cd src/backend
            mvn test

  deploy-docker-image:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - checkout
      - docker/install-docker-tools
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: "Build and push Docker image"
          command: |
            cd src/backend
            docker build \
              --build-arg SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME \
              --build-arg SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD \
              --build-arg SPRING_DATASOURCE_HOSTNAME=$SPRING_DATASOURCE_HOSTNAME \
              --build-arg SPRING_DATASOURCE_PORT=$SPRING_DATASOURCE_PORT \
              --build-arg SPRING_DATASOURCE_DBNAME=$SPRING_DATASOURCE_DBNAME \
              --build-arg SPRING_DATASOURCE_SSL=$SPRING_DATASOURCE_SSL \
              -t fisiomais.azurecr.io/fisiomais:latest .
            docker login -u $DOCKER_USER -p $DOCKER_PASS fisiomais.azurecr.io
            docker push fisiomais.azurecr.io/fisiomais:latest

workflows:
  test-and-deploy:
    jobs:
      - build-and-test
      - deploy-docker-image:
          requires:
            - build-and-test
