name: Backend Deploy CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      run: |
        docker login -u ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}

    - name: Build and push Docker image
      run: |
        docker tag ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_APP_NAME }} ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_APP_NAME }}:latest
        docker buildx create --use
        docker buildx build -t ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_APP_NAME }}:latest -f src/backend/Dockerfile
        docker push ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_APP_NAME }}:latest

env:
  DOCKER_CLI_ACI_VERSION: 1.19.0
  DOCKER_BUILDKIT: 1
